cluster: "uge_submit.py"
cluster-status: "uge_status.py"
jobscript: "uge_jobscript.sh"
{%- if cookiecutter.directory != "" %}
directory: "{{cookiecutter.directory}}"
{%- endif %}
{%- if cookiecutter.conda_prefix != "" %}
conda-prefix: "{{cookiecutter.conda_prefix}}"
{%- endif %}
{%- if cookiecutter.cluster_cancel != "" %}
cluster-cancel: "{{cookiecutter.cluster_cancel}}"
{%- endif %}
restart-times: "{{cookiecutter.restart_times}}"
use-conda: "{{cookiecutter.use_conda}}"
use-singularity: "{{cookiecutter.use_singularity}}"
keep-going: "{{cookiecutter.keep_going}}"
printshellcmds: "{{cookiecutter.print_shell_commands}}"
rerun-incomplete: "{{cookiecutter.rerun_incomplete}}"
jobs: "{{cookiecutter.jobs}}"
latency-wait: "{{cookiecutter.latency_wait}}"
max-status-checks-per-second: "{{cookiecutter.max_status_checks_per_second}}"
max-jobs-per-second: "{{cookiecutter.max_jobs_per_second}}"
local-cores: 1
